# Generated by Django 5.1.4 on 2026-06-18 01:33

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dcim", "0200_populate_mac_addresses"),
        ("extras", "0122_charfield_null_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="EolSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("api_key_ciphertext", models.TextField(blank=True, default="")),
                ("api_key_last4", models.CharField(blank=True, default="", max_length=4)),
                ("base_url", models.URLField(default="https://eol.network/api/v1/")),
                ("sync_enabled", models.BooleanField(default=False)),
                ("sync_interval_hours", models.PositiveIntegerField(default=24)),
                ("auto_accept_tiers", models.JSONField(default=list)),
                ("review_tiers", models.JSONField(default=list)),
                ("sync_targets", models.CharField(default="in_use", max_length=20)),
                ("last_sync_started", models.DateTimeField(blank=True, null=True)),
                ("last_sync_finished", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(default="never", max_length=20)),
                ("last_sync_message", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "EOL settings",
                "verbose_name_plural": "EOL settings",
            },
        ),
        migrations.CreateModel(
            name="LifecycleProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder
                    ),
                ),
                ("vendor_slug", models.CharField(max_length=100)),
                ("product_id", models.CharField(max_length=200)),
                ("product_name", models.CharField(blank=True, default="", max_length=200)),
                ("product_type", models.CharField(blank=True, default="", max_length=100)),
                ("applicable_series", models.JSONField(blank=True, default=list)),
                ("series_slug", models.CharField(blank=True, default="", max_length=100)),
                ("category", models.CharField(blank=True, default="", max_length=50)),
                ("lifecycle_status", models.CharField(blank=True, default="", max_length=20)),
                ("announcement_date", models.DateField(blank=True, null=True)),
                ("end_of_sale_date", models.DateField(blank=True, null=True)),
                ("last_date_of_support", models.DateField(blank=True, null=True)),
                ("end_of_sw_maintenance_date", models.DateField(blank=True, null=True)),
                ("end_of_vuln_security_support_date", models.DateField(blank=True, null=True)),
                ("end_of_routine_failure_analysis_date", models.DateField(blank=True, null=True)),
                ("replacement_product", models.CharField(blank=True, default="", max_length=200)),
                (
                    "replacement_product_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("kev_exposed", models.BooleanField(default=False)),
                ("kev_count", models.PositiveIntegerField(default=0)),
                ("kev_cve_ids", models.JSONField(blank=True, default=list)),
                ("kev_catalog_version", models.CharField(blank=True, default="", max_length=50)),
                ("kev_updated_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField(blank=True, default="")),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
                ),
            ],
            options={
                "ordering": ("vendor_slug", "product_id"),
            },
        ),
        migrations.CreateModel(
            name="DeviceTypeMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder
                    ),
                ),
                ("match_method", models.CharField(default="none", max_length=10)),
                ("match_confidence", models.CharField(blank=True, default="", max_length=10)),
                ("match_query", models.CharField(blank=True, default="", max_length=200)),
                ("vendor_resolved", models.CharField(blank=True, default="", max_length=100)),
                ("is_overridden", models.BooleanField(default=False)),
                ("last_matched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eol_mapping",
                        to="dcim.devicetype",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mappings",
                        to="netbox_eol.lifecycleproduct",
                    ),
                ),
            ],
            options={
                "ordering": ("device_type",),
            },
        ),
        migrations.CreateModel(
            name="ManufacturerVendorMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder
                    ),
                ),
                ("vendor_slug", models.CharField(max_length=100)),
                ("source", models.CharField(default="learned", max_length=10)),
                (
                    "manufacturer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eol_vendor_map",
                        to="dcim.manufacturer",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
                ),
            ],
            options={
                "ordering": ("manufacturer",),
            },
        ),
        migrations.AddConstraint(
            model_name="lifecycleproduct",
            constraint=models.UniqueConstraint(
                fields=("vendor_slug", "product_id"), name="netbox_eol_product_unique"
            ),
        ),
    ]
